# <center>Keras Basics

## 1) Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras

Using TensorFlow backend.


## 2) Loading the built-in Iris dataset

Scikit Learn offers some inbuilt datasets. Iris is one of them.

If you want to download it from kaggle,you are free to do.
Here is the link:  https://www.kaggle.com/uciml/iris

In [0]:
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

## 3) Splitting into features and labels

In [5]:
# Extracting features and labels

X = iris.data
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 3.1) One Hot Encoding on Y_label

In [0]:
# Converting the label into one hot encoder
# Class 0 --->  [1,0,0]
# Class 1 --->  [0,1,0]
# Class 2 --->  [0,0,1]

from keras.utils import to_categorical

y = to_categorical(y)

In [8]:
y.shape

(150, 3)

In [9]:
y[:10]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

## 4) Splitting the data into train and test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)

In [11]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((100, 4), (50, 4), (100, 3), (50, 3))

### 4.1) Feature Scaling

In [12]:
from sklearn.preprocessing import MinMaxScaler

mmx = MinMaxScaler()
mmx.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
Scaled_X_train = mmx.transform(X_train)
Scaled_X_test = mmx.transform(X_test)

## 5) Building the model using Keras

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


## 6) Training the model

In [18]:
# Play around with number of epochs as well!
model.fit(Scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
 - 2s - loss: 1.1303 - accuracy: 0.3300
Epoch 2/150
 - 0s - loss: 1.1259 - accuracy: 0.3600
Epoch 3/150
 - 0s - loss: 1.1225 - accuracy: 0.3700
Epoch 4/150
 - 0s - loss: 1.1192 - accuracy: 0.3600
Epoch 5/150
 - 0s - loss: 1.1161 - accuracy: 0.3500
Epoch 6/150
 - 0s - loss: 1.1129 - accuracy: 0.3600
Epoch 7/150
 - 0s - loss: 1.1104 - accuracy: 0.3500
Epoch 8/150
 - 0s - loss: 1.1080 - accuracy: 0.3800
Epoch 9/150
 - 0s - loss: 1.1059 - accuracy: 0.3600
Epoch 10/150
 - 0s - loss: 1.1040 - accuracy: 0.3600
Epoch 11/150
 - 0s - loss: 1.1023 - accuracy: 0.3700
Epoch 12/150
 - 0s - loss: 1.1007 - accuracy: 0.3700
Epoch 13/150
 - 0s - loss: 1.0988 - accuracy: 0.3700
Epoch 14/150
 - 0s - loss: 1.0972 - accuracy: 0.3700
Epoch 15/150
 - 0s - loss: 1.0957 - accuracy: 0.3500
Epoch 16/150
 - 0s - loss: 1.0940 - accuracy: 0.3500
Epoch 17/150
 - 0s - loss: 1.0924 - accuracy: 0.3500
Epoch 18/150
 - 0s - loss: 1.0908 - accuracy: 0.3600
Epoch 19/150
 - 0s - loss: 1.0890 - accuracy: 0.3900
Ep

## 7) Testing the model on Test Set

In [19]:
model.predict(Scaled_X_test)

array([[6.86001591e-03, 5.76077521e-01, 4.17062461e-01],
       [9.59403396e-01, 2.49679517e-02, 1.56285930e-02],
       [4.16121111e-06, 1.06692336e-01, 8.93303514e-01],
       [6.55385293e-03, 5.22652090e-01, 4.70794022e-01],
       [7.27152103e-04, 3.88813704e-01, 6.10459208e-01],
       [9.19114172e-01, 5.02966531e-02, 3.05890962e-02],
       [3.48074771e-02, 6.49512351e-01, 3.15680206e-01],
       [1.32908739e-04, 1.89685360e-01, 8.10181737e-01],
       [5.26652089e-04, 3.21001917e-01, 6.78471386e-01],
       [1.38211530e-02, 6.10616565e-01, 3.75562221e-01],
       [1.16287160e-03, 3.41102123e-01, 6.57735050e-01],
       [9.55079436e-01, 2.58950796e-02, 1.90255288e-02],
       [9.53419685e-01, 2.83353254e-02, 1.82449352e-02],
       [9.58239317e-01, 2.40896381e-02, 1.76710412e-02],
       [9.80863094e-01, 1.08147636e-02, 8.32209457e-03],
       [7.65910977e-03, 5.35921395e-01, 4.56419528e-01],
       [2.85136281e-04, 2.33955085e-01, 7.65759826e-01],
       [1.54909333e-02, 6.25323

In [22]:
model.predict_classes(Scaled_X_test)   # It will return the index of the maximum value

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

In [0]:
predictions = model.predict_classes(Scaled_X_test)

In [24]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])